SELECT * FROM TRANSACTION_VIEW
---- TRUNCATE TABLE TRANSACTION_VIEW

----INSERT INTO TRANSACTION_VIEW
SELECT  tmCOR_fcName, ttODH_ftDate, ttODH_fnNetAmt, tmCOM_fcName, tmDCB_fcName, ttODH_fcCode, tmBRN_fcCOMID
FROM   dbo.vtODH


SELECT TOP 100
*
FROM vtODH

SELECT TOP 100
*
FROM vtODD



SELECT distinct
tmDCB_fcName
FROM TRANSACTION_VIEW
group by tmDCB_fcName

SELECT distinct
tmDCB_fcName,COUNT(tmDCB_fcName)
FROM TRANSACTION_VIEW
group by tmDCB_fcName


SELECT TOP 10 *
FROM TRANSACTION_VIEW


/*
	จำนวน BILL ต่อโครงการ ตามปีและเดือน
*/

SELECT
DATEPART(YEAR,ttODH_ftDate) AS 'THEYEAR',
DATEPART(MONTH,ttODH_ftDate) AS 'TheMonth',
tmCOM_fcName,
CASE WHEN tmDCB_fcName = 'BILL' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'BILL' 
FROM TRANSACTION_VIEW
INNER JOIN tmCOM ON tmCOM.fcID = TRANSACTION_VIEW.tmBRN_fcCOMID AND tmCOM.fcIsActive = 'Y'
WHERE tmDCB_fcName = 'BILL'
AND DATEPART(YEAR,ttODH_ftDate) BETWEEN '2018' AND '2021'
GROUP BY DATEPART(YEAR,ttODH_ftDate),DATEPART(MONTH,ttODH_ftDate),tmCOM_fcName,tmDCB_fcName,tmCOM_fcName
ORDER BY DATEPART(YEAR,ttODH_ftDate) ASC ,DATEPART(MONTH,ttODH_ftDate) ASC


/*
	จำนวน BILL ต่อโครงการ ตามปี
*/

SELECT
tmCOM_fcName
,CASE WHEN DATEPART(YEAR,ttODH_ftDate) ='2018' THEN COUNT(ttODH_fcCode) ELSE 0 END AS '2018'
,CASE WHEN DATEPART(YEAR,ttODH_ftDate) ='2019' THEN COUNT(ttODH_fcCode) ELSE 0 END AS '2019'
,CASE WHEN DATEPART(YEAR,ttODH_ftDate) ='2020' THEN COUNT(ttODH_fcCode) ELSE 0 END AS '2020'
,CASE WHEN DATEPART(YEAR,ttODH_ftDate) ='2021' THEN COUNT(ttODH_fcCode) ELSE 0 END AS '2021'
--CASE WHEN tmDCB_fcName = 'BILL' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'BILL' 
FROM TRANSACTION_VIEW
INNER JOIN tmCOM ON tmCOM.fcID = TRANSACTION_VIEW.tmBRN_fcCOMID AND tmCOM.fcIsActive = 'Y'
WHERE tmDCB_fcName = 'BILL'
AND DATEPART(YEAR,ttODH_ftDate) BETWEEN '2018' AND '2021'
GROUP BY DATEPART(YEAR,ttODH_ftDate),DATEPART(MONTH,ttODH_ftDate),tmCOM_fcName,tmDCB_fcName,tmCOM_fcName
ORDER BY DATEPART(YEAR,ttODH_ftDate) ASC ,DATEPART(MONTH,ttODH_ftDate) ASC

-------------------------------------------------------------------

SELECT 
tmCOM_fcName
,CASE WHEN tmDCB_fcName ='BILL' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'BILL'
,CASE WHEN tmDCB_fcName ='JOBORDER' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'JOBORDER'
,CASE WHEN tmDCB_fcName ='JOBPM' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'JOBPM'
,CASE WHEN tmDCB_fcName ='NOTICE' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'NOTICE'
,CASE WHEN tmDCB_fcName ='PO' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'PO'
,CASE WHEN tmDCB_fcName ='RETURN' THEN COUNT(ttODH_fcCode) ELSE 0 END AS 'RETURN'
FROM TRANSACTION_VIEW
INNER JOIN tmCOM ON tmCOM.fcID = TRANSACTION_VIEW.tmBRN_fcCOMID AND tmCOM.fcIsActive = 'Y'
GROUP BY tmCOM_fcName,tmDCB_fcName
ORDER BY tmCOM_fcName



-------------------------------------------------------------------

SELECT 
DATEPART(YEAR,ttODH_ftDate) AS THEYEARS
,CASE WHEN tmDCB_fcName ='BILL' THEN COUNT(ttODH_fcCode) END AS 'BILL'
--,CASE WHEN tmDCB_fcName ='JOBORDER' THEN COUNT(tmBRN_fcCOMID) ELSE 0 END AS 'JOBORDER'
--,CASE WHEN tmDCB_fcName ='JOBPM' THEN COUNT(tmBRN_fcCOMID) ELSE 0 END AS 'JOBPM'
--,CASE WHEN tmDCB_fcName ='NOTICE' THEN COUNT(tmBRN_fcCOMID) ELSE 0 END AS 'NOTICE'
--,CASE WHEN tmDCB_fcName ='PO' THEN COUNT(tmBRN_fcCOMID) ELSE 0 END AS 'PO'
--,CASE WHEN tmDCB_fcName ='RETURN' THEN COUNT(tmBRN_fcCOMID) ELSE 0 END AS 'RETURN'
FROM TRANSACTION_VIEW
INNER JOIN tmCOM ON tmCOM.fcID = TRANSACTION_VIEW.tmBRN_fcCOMID AND tmCOM.fcIsActive = 'Y'
--WHERE    DATEPART(YEAR,ttODH_ftDate) BETWEEN '2018' AND '2021'
WHERE    DATEPART(YEAR,ttODH_ftDate) = '2018' 
GROUP BY DATEPART(YEAR,ttODH_ftDate),tmDCB_fcName
--,DATEPART(MONTH,ttODH_ftDate),tmDCB_fcName
ORDER BY DATEPART(YEAR,ttODH_ftDate)


 