/*
	จำนวนเอกสารแต่ละโครงการ
*/
select 
fcName
,BILLTOTAL
,NOTICETOTAL
,JOBTOTAL		
,POSTTOTAL	
,INVTOTAL
,INVCNTOTAL
,PRTOTAL
,POTOTAL
,PITOTAL
,PITOTAL
,PVTOTAL
from TOTALUSES_All



/*
  จำนวนข้อมูลเอกสารแบ่งตามปี
*/
SELECT
DATEPART(YEAR,ftCreateDate) AS 'THEYEARS'
,COUNT(BILLTOTAL)  AS 'BILLTOTAL'
,COUNT(NOTICETOTAL)	AS 'NOTICETOTAL'
,COUNT(JOBTOTAL)	AS 'JOBTOTAL'	
,COUNT(POSTTOTAL)	AS 'POSTTOTAL'	
,COUNT(INVTOTAL)	AS 'INVTOTAL'
,COUNT(INVCNTOTAL)	AS 'INVCNTOTAL'
,COUNT(PRTOTAL)	AS 'PRTOTAL'
,COUNT(POTOTAL)	AS 'POTOTAL'
,COUNT(PITOTAL)	AS 'PITOTAL'
,COUNT(PITOTAL)	AS 'PITOTAL'
,COUNT(PVTOTAL)	AS 'PVTOTAL'
FROM TOTALUSES_All
WHERE DATEPART(YEAR,ftCreateDate) BETWEEN '2018' AND '2021'
GROUP BY DATEPART(YEAR,ftCreateDate)
ORDER BY DATEPART(YEAR,ftCreateDate)


/*
	จำนวนเอกสารที่มีการใช้งาน ต่อปี
*/
SELECT
DATEPART(YEAR,ftCreateDate) AS 'THEYEARS'
,SUM(BILLTOTAL)  AS 'BILLTOTAL'
,SUM(NOTICETOTAL)	AS 'NOTICETOTAL'
,SUM(JOBTOTAL)	AS 'JOBTOTAL'	
,SUM(POSTTOTAL)	AS 'POSTTOTAL'	
,SUM(INVTOTAL)	AS 'INVTOTAL'
,SUM(INVCNTOTAL)	AS 'INVCNTOTAL'
,SUM(PRTOTAL)	AS 'PRTOTAL'
,SUM(POTOTAL)	AS 'POTOTAL'
,SUM(PITOTAL)	AS 'PITOTAL'
,SUM(PITOTAL)	AS 'PITOTAL'
,SUM(PVTOTAL)	AS 'PVTOTAL'
FROM TOTALUSES_All
WHERE DATEPART(YEAR,ftCreateDate) BETWEEN '2018' AND '2021'
GROUP BY DATEPART(YEAR,ftCreateDate)
ORDER BY DATEPART(YEAR,ftCreateDate)



